# Generated by Django 2.2.12 on 2021-11-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.IntegerField(blank=True, max_length=150, null=True)),
                ('product_id', models.IntegerField(blank=True, max_length=150, null=True)),
                ('sku_name', models.CharField(blank=True, max_length=450, null=True)),
                ('price', models.FloatField(blank=True, max_length=450, null=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=450, null=True)),
                ('salt_name', models.CharField(blank=True, max_length=450, null=True)),
                ('drug_form', models.CharField(blank=True, max_length=450, null=True)),
                ('Pack_size', models.CharField(blank=True, max_length=450, null=True)),
                ('strength', models.CharField(blank=True, max_length=450, null=True)),
                ('product_banned_flag', models.BooleanField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=450, null=True)),
                ('price_per_unit', models.FloatField(blank=True, max_length=450, null=True)),
            ],
        ),
    ]
