# Generated by Django 2.2.12 on 2021-11-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='product_banned_flag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
