# Generated by Django 2.2.12 on 2021-11-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20211113_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
